### ISSUE TITLE
[Enhancement] Change WC data from ValFields to DynVars

### ISSUE THREAD

**Issue by dfgHiatus** [Ruz-eh/NeosWCFaceTrack#1]
Currently, NWC uses ValFields to store incoming sensor data. These are unreliable, as they are known to shuffle on spawn and are unnameable.

Using DynVars would enable us to name our data, and expose it to NeosVR's robust DynVar system.

**Comment by Ruz-eh** [comment]
Right, I'll get on it!

**Comment by Ruz-eh** [comment]
All variables were transferred to dynamic vars, closing
